-- 코드를 작성해주세요
SELECT D1.ID, D1.GENOTYPE, D2.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA D1 JOIN ECOLI_DATA D2
ON D1.PARENT_ID = D2.ID  -- 1. 부모-자식 관계 연결
WHERE (D1.GENOTYPE & D2.GENOTYPE) = D2.GENOTYPE  -- 2. 자식이 부모의 형질을 모두 가졌는지 확인
ORDER BY D1.ID ASC;